config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"
  devise_for :users 
  
  
    resources :clothes

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'outer' },
    { id: 2, name: 'tops' },
    { id: 3, name: 'pants' },
    { id: 4, name: 'shoes' },
    { id: 5, name: 'items' },
  ]
  include ActiveHash::Associations
  has_many :clothes
end

app/models/clothe.rb
class Clothe < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  validates :image, presence: true
  validates :category_id, numericality: { other_than: 0 }
  validates :description, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
      { id: 1, name: '--' },
      { id: 2, name: 'Men'},
      { id: 3, name: 'Wemen'}
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  with_options presence: true do
    validates :image
    validates :detail
  end

  with_options numericality: { other_than: 1 } do
    validates :season_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :season

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      { id: 1, name: '--' },{id: 2, name: '北海道'}, {id: 3, name: '青森県'}, 
      {id: 4, name: '岩手県'},{id: 5, name: '宮城県'}, {id: 6, name: '秋田県'}, 
      {id: 7, name: '山形県'},{id: 8, name: '福島県'}, {id: 9, name: '茨城県'}, 
      {id: 10, name: '栃木県'},{id: 11, name: '群馬県'}, {id: 12, name: '埼玉県'}, 
      {id: 13, name: '千葉県'},{id: 14, name: '東京都'}, {id: 15, name: '神奈川県'}, 
      {id: 16, name: '新潟県'},{id: 17, name: '富山県'}, {id: 18, name: '石川県'},
      {id: 19, name: '福井県'},{id: 20, name: '山梨県'}, {id: 21, name: '長野県'}, 
      {id: 22, name: '岐阜県'},{id: 23, name: '静岡県'}, {id: 24, name: '愛知県'},
      {id: 25, name: '三重県'},{id: 26, name: '滋賀県'}, {id: 27, name: '京都府'}, 
      {id: 28, name: '大阪府'},{id: 29, name: '兵庫県'}, {id: 30, name: '奈良県'}, 
      {id: 31, name: '和歌山県'},{id: 32, name: '鳥取県'}, {id: 33, name: '島根県'},
      {id: 34, name: '岡山県'},{id: 35, name: '広島県'}, {id: 36, name: '山口県'}, 
      {id: 37, name: '徳島県'},{id: 38, name: '香川県'}, {id: 39, name: '愛媛県'}, 
      {id: 40, name: '高知県'},{id: 41, name: '福岡県'}, {id: 42, name: '佐賀県'}, 
      {id: 43, name: '長崎県'},{id: 44, name: '熊本県'}, {id: 45, name: '大分県'}, 
      {id: 46, name: '宮崎県'},{id: 47, name: '鹿児島県'}, {id: 48, name: '沖縄県'}
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/season.rb
class Season < ActiveHash::Base
  self.data = [
      { id: 1, name: '--' },
      { id: 2, name: 'spring'},
      { id: 3, name: 'summer'},
      { id: 4, name: 'autumn'},
      { id: 5, name: 'winter'}
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :encrypted_password
    validates :password,
      format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i}
  end

  with_options numericality: { other_than: 1 } do
    validates :gender_id
    validates :prefecture_id
  end

  has_many :clothes
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
    username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :gender_id, :prefecture_id])
  end
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  before_action :set_clothe, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    clothes = @clothes
    @myclothes = current_user.clothes
    @search = @myclothes.ransack(params[:q])
    @myclothes = @search.result
    
  end

  def new
    @clothe = Clothe.new
  end

  def create
    @clothe = Clothe.new(clothe_params)
    if @clothe.save
      redirect_to clothes_path
    else
      render :new
    end
  end

    def show
    end

    def edit
    end

    def update
      if @clothe.update(clothe_without_image)
        redirect_to clothe_path
      else
        render :edit
    end
  end

    def destroy
      @clothe.destroy
      redirect_to clothes_path
    end

  private

  def clothe_params
    params.require(:clothe).permit(:description, :category_id, :image ).merge(user_id: current_user.id)
  end

  def clothe_without_image
    params.require(:clothe).permit(:description, :category_id).merge(user_id: current_user.id)
  end

  def set_clothe
    @clothe = Clothe.find(params[:id])
  end

  def move_to_root
    redirect_to root_path unless current_user.id == @clothe.user_id
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_params

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @posts = Post.all
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @posts = Post.all
  end

  private
  def post_params
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all
    @search = Post.ransack(params[:q])
    @posts = @search.result
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @like = Like.new
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @post.update(post_without_image)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:detail, :season_id, :image ).merge(user_id: current_user.id)
  end

  def post_without_image
    params.require(:post).permit(:detail, :season_id).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_root
    redirect_to root_path unless current_user.id == @post.user_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothe_helper.rb
module ClotheHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], url: post_comments_path(@post) ) do |f| %>
    <%= f.text_area :text, class: "input-mysize" %>
    <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right"%>
<% end %>

app/views/comments/_index.html.erb
<!-- コメント内容(２件) ------------------------------------------------------------------>
<%= comments.count %>件コメント
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<% comments.first(2).each do |comment| %>
  <% unless comment.id.nil? %>
    <li class="comment-container">
        <div class="comment-box">
            <div class="comment-text">
                <p><%= link_to "@#{comment.user.nickname}", "#" %></p>
                <div class="comment-entry">
                    <%= comment.text %>
                    <% if comment.user == current_user %>
                        <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                            <i class="fas fa-trash" style="color: black;"></i>
                        <% end %>
                    <% end %>
                </div>
                <span class="comment-date pull-right">
                      <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                </span>
            </div>
        </div>
    </li>
  <% end %>
<% end %>
<!-- コメント内容(3件目以降) ------------------------------------------------------------------>
    <div class="collapse" id="collapseExample">
            <% comments.offset(2).each do |comment| %>
              <% unless comment.id.nil? %>
                <li class="comment-container">
                    <div class="comment-box">
                        <div class="comment-text">
                            <p><%= link_to "@#{comment.user.nickname}", "#" %></p>
                            <div class="comment-entry">
                                <%= comment.text %>
                                <% if comment.user == current_user %>
                                    <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                                        <i class="fas fa-trash" style="color: black;"></i>
                                    <% end %>
                                <% end %>
                            </div>
                            <span class="comment-date pull-right">
                                  <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                            </span>
                        </div>
                    </div>
                </li>
              <% end %>
            <% end %>
    </div>

app/views/comments/create.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')

app/views/likes/_like.html.erb
<% if user_signed_in? %>
    <% if current_user.already_liked?(@post) %>
        <%= link_to post_likes_path(post), method: :delete, id: "like-button-#{post.id}", remote: true do %>
                <i class="fab fa-gratipay fa-2x"></i>
                <span class="fa-layers-counter" ><%= post.likes.count %></span>
        <% end %>
    <% else %>
        <%= link_to post_likes_path(post), method: :post, id: "like-button-#{post.id}", remote: true do %>
          <i class="fab fa-gratipay fa-2x"></i>
          <span class="fa-layers-counter" ><%= post.likes.count %></span>
        <% end %>
    <% end %>
<% else %>
        <i class="fab fa-gratipay fa-2x"></i>
    <span class="fa-layers-counter" ><%= post.likes.count %></span>
<% end %>

app/views/likes/create.js.erb
$("#like-button").html(
  '<%=j render partial: "likes/like", locals: { post: @post, posts: @posts, like: @like, likes: @likes} %>'
);

app/views/likes/destroy.js.erb
$("#like-button").html(
  '<%=j render partial: "likes/like", locals: { post: @post, posts: @posts, like: @like, likes: @likes} %>'
);

app/views/posts/edit.html.erb
<div class = "post_edit">
  <%= link_to image_tag("logo.png", class:"logo"), root_path %>
  <%= form_with model: @post, local: true do |f| %>
  <div class="image_content">
    <%= image_tag @post.image ,class:"img-thumbnail" %>
  </div>
    <div class="offset-md-4 col-md-4 text-left ">
      <div class="form-log"></br>
          <h4 class = 'title-text'>Edit</h4>
          <%= render 'shared/error_messages', model: f.object %>
          <%= f.collection_select(:season_id, Season.all, :id, :name, {:include_blank => "Season"}, {class:"form-control input-sm chat-input"}) %>
          <%= f.text_area :detail, class: "form-control input-sm chat-input", placeholder:"detail",maxlength:"1000" %>
        <div class = "wrapper">
          <span class="new_clothe_btn">
          <%=link_to 'Back', post_path(@post.id), class:"btn btn-danger btn-md" %>
          <%= f.submit "Save" ,class:"btn btn-danger btn-md" %>
          </span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class = "clothe-header">
  <%= link_to image_tag("logo.png", class:"logo"), root_path %>
  <%= link_to( new_post_path, class: 'post-btn') do %>
    <div class='new-save-link'>New save</div>
  <% end %>
  <div class = "category-content">
    <div class = "category-search-form">
<%= search_form_for @search, url: posts_path do |f| %>
      <div class = "season-search">
      <%= f.collection_select :season_id_eq, Season.where.not(id: 1), :id, :name, include_blank: "Season search", class: "cate_btn" %>
      <%= f.submit "Search", class: "btn btn-secondary" %>
      </div>
<% end %>
    </div>
  </div>
</div>

<div class="previews">
  <div class="slider">
    <% @posts.each do |post| %>
      <%= link_to post_path(post.id) do %>
      <%= image_tag (post.image), class: "d-block w-100" %>
      <% end %>
    <% end %>
  </div>
</div>

<div class = "clothes-all">
  <div class='clothe-img-content'>
  <% @posts.each do |post| %>
        <%= link_to post_path(post.id) do %>
        <%= image_tag(post.image, class: "img-thum") %>
    <% end %>
  <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<div class = "new_post_back_image">
<%= form_with model: @post, local: true do |f| %>
  <div class="container">
    <div class = "row ">
      <div class="offset-md-2 col-md-5 text-left ">
        <div class="form-log"></br>
          <h4 class = 'title-text'>New save</h4>
          <%= render 'shared/error_messages', model: f.object %>
          <label class = "form-control input-sm chat-input" >
          <%= f.file_field :image, class: "new_clothe_image" %>
          </label>
          <%= f.collection_select(:season_id, Season.all, :id, :name, {:include_blank => "Season"}, {class:"form-control input-sm chat-input"}) %>
          <%= f.text_area :detail, class: "form-control input-sm chat-input", placeholder:"detail",maxlength:"1000" %>
          <div class = "wrapper">
            <span class="new_clothe_btn">
            <%=link_to 'Back', posts_path, class:"btn btn-danger btn-md" %>
            <%= f.submit "New save" ,class:"btn btn-danger btn-md" %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class = "post_show">
<%= link_to image_tag("logo.png", class:"logo"), root_path %>
  <div class="image_content">
  <%= image_tag @post.image ,class:"img-thumbnail" %>
  </div>

<div class="content_range">
  <div class = "content_cate">
  <p>Season</p>
  <p class = "season_position"><%= @post.season.name %></p>
  </div>
  <div class="content_desc">
  <p>Description</p>
  <p><%= @post.detail %><p>
  </div>
</div>

<div id="like-button", class="like-button">
  <%= render 'likes/like', post: @post %>
</div>
  <div class="clothe_manage">
    <div class = "edit_space">
    <% if current_user == @post.user%>
      <%= link_to 'Back', posts_path, class: :clothe_btn %>
      <%= link_to "Edit", edit_post_path(@post.id), class: :clothe_btn %>
      <%= link_to "Delete", post_path(@post.id), method: :delete, class: :clothe_btn %>
      <% else %>
      <%= link_to 'Back', posts_path, class: :back_btn %>
      <% end %>
      </div>
  </div>

<div class="row">
    <ul>
      <li class="comment-create">
        <h3 class="text-left title">comment</h3>
      </li>
      <li id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments } %>
      </li>
    </ul>
    <hr>
    <% if user_signed_in? %>
        <div class="comment-create">
            <h3 class="text-left">Post comment</h3>
            <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
        </div>
    <% end %>
</div>