config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"
  devise_for :users 
  
  
    resources :clothes

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/clothe.rb
class Clothe < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  validates :image, presence: true
  validates :category_id, numericality: { other_than: 0 }
  validates :description, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  before_action :set_clothe, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    clothes = @clothes
    @myclothes = current_user.clothes
    @search = @myclothes.ransack(params[:q])
    @myclothes = @search.result
    
  end

  def new
    @clothe = Clothe.new
  end

  def create
    @clothe = Clothe.new(clothe_params)
    if @clothe.save
      redirect_to clothes_path
    else
      render :new
    end
  end

    def show
    end

    def edit
    end

    def update
      if @clothe.update(clothe_without_image)
        redirect_to clothe_path
      else
        render :edit
    end
  end

    def destroy
      @clothe.destroy
      redirect_to clothes_path
    end

  private

  def clothe_params
    params.require(:clothe).permit(:description, :category_id, :image ).merge(user_id: current_user.id)
  end

  def clothe_without_image
    params.require(:clothe).permit(:description, :category_id).merge(user_id: current_user.id)
  end

  def set_clothe
    @clothe = Clothe.find(params[:id])
  end

  def move_to_root
    redirect_to root_path unless current_user.id == @clothe.user_id
  end

end

app/helpers/clothe_helper.rb
module ClotheHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/views/clothes/edit.html.erb
<div class = "edit_content">
  <%= link_to image_tag("logo.png", class:"logo"), root_path %>
  <%= form_with model: @clothe, local: true do |f| %>
  <div class="image_content">
    <%= image_tag @clothe.image ,class:"img-thumbnail" %>
  </div>
    <div class="offset-md-4 col-md-4 text-left ">
      <div class="form-log"></br>
          <h4 class = 'title-text'>Edit</h4>
          <%= render 'shared/error_messages', model: f.object %>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => "Category"}, {class:"form-control input-sm chat-input"}) %>
          <%= f.text_area :description, class: "form-control input-sm chat-input", placeholder:"description",maxlength:"1000" %>
        <div class = "wrapper">
          <span class="new_clothe_btn">
          <%=link_to 'Back', clothe_path(@clothe.id), class:"btn btn-danger btn-md" %>
          <%= f.submit "Save" ,class:"btn btn-danger btn-md" %>
          </span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/clothes/index.html.erb
<div class = "clothe-header">
  <%= link_to image_tag("logo.png", class:"logo"), root_path %>
  <%= link_to( new_clothe_path, class: 'post-btn') do %>
    <div class='new-save-link'>New save</div>
  <% end %>
  <div class = "category-content">
    <div class = "category-search-form">
<%= search_form_for @search, url: clothes_path do |f| %>
      <div class = "category-search">
      <%= f.collection_select :category_id_eq, Category.where.not(id: 0), :id, :name, include_blank: "Category search", class: "cate_btn" %>
     <%= f.submit "Search", class: "btn btn-secondary" %>
     </div>
<% end %>
    </div>
  </div>
</div>

<div class = "clothes-all">
  <div class='clothe-img-content'>
  <% @myclothes.each do |myclothe| %>
      <%= link_to clothe_path(myclothe.id) do %>
      <%= image_tag(myclothe.image , class: "img-thum")%>
    <% end %>
  <% end %>
  </div>
</div>

app/views/clothes/new.html.erb
<div class = "new_clothe_back_image">
<%= form_with model: @clothe, local: true do |f| %>
  <div class="container">
    <div class = "row ">
      <div class="offset-md-2 col-md-5 text-left ">
        <div class="form-log"></br>
          <h4 class = 'title-text'>New save</h4>
          <%= render 'shared/error_messages', model: f.object %>
          <label class = "form-control input-sm chat-input" >
          <%= f.file_field :image, class: "new_clothe_image" %>
          </label>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => "Category"}, {class:"form-control input-sm chat-input"}) %>
          <%= f.text_area :description, class: "form-control input-sm chat-input", placeholder:"description",maxlength:"1000" %>
          <div class = "wrapper">
            <span class="new_clothe_btn">
            <%=link_to 'Back', clothes_path, class:"btn btn-danger btn-md" %>
            <%= f.submit "New save" ,class:"btn btn-danger btn-md" %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/clothes/show.html.erb
<div class = "show_content">
<%= link_to image_tag("logo.png", class:"logo"), root_path %>
<div class="image_content">
  <%= image_tag @clothe.image ,class:"img-thumbnail" %>
</div>

<div class = content_range>
<div class="content_cate">
  <p>Category</p>
  <p><%= @clothe.category.name %></p>
  </div>
  <div class="content_desc">
  <p>Description</p>
  <p><%= @clothe.description %></p>
  </div>
</div>

  <div class="clothe_manage">
    <div class = "edit_space">
      <% if current_user == @clothe.user%>
      <%= link_to 'Back', clothes_path, class: :clothe_btn %>
      <%= link_to "Edit", edit_clothe_path(@clothe.id), class: :clothe_btn %>
      <%= link_to "Delete", clothe_path(@clothe.id), method: :delete, class: :clothe_btn %>
      <% else %>
      <%= link_to 'Back', clothes_path, class: :back_btn %>
      <% end %>
      </div>
  </div>
</div>